name: Flutter CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        platform: x64
    - name: Setup Ninja
      run: sudo apt-get install -y ninja-build
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12'
    - uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '2.0.3'
    - name: Build
      run: |
        flutter config --enable-linux-desktop
        flutter pub get
        flutter pub run intl_utils:generate
        flutter pub run build_runner build --delete-conflicting-outputs
        flutter build linux
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: build/linux/release/bundle/
